aquanine/urls.py
from django.conf.urls import url, include, patterns
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('shop.urls', namespace="shop")),
    url(r'^admin/', include('backend.urls', namespace="backend")),
    url(r'^backend/', admin.site.urls),
    url(r'^froala_editor/', include('froala_editor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if DEBUG is True it will be served automatically
if settings.DEBUG is False:
    urlpatterns += patterns('',
            url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
            url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

backend/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from backend import views
from backend.pages import announces
from backend.pages import blogs
from backend.pages import members
from backend.pages import orders

from backend.pages import products

urlpatterns = [
    # url('^',include('django.contrib.auth.urls')),
    url(r'^$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'backend:login'}, name='logout'),
    url(r'^product/$', products.ProductListView.as_view(), name='product_list'),
    url(r'^product/new/$', products.ProductAddView.as_view(), name='product_add'),
    url(r'^product/(?P<pk>[0-9]+)/$', products.ProductDetailView.as_view(), name='product_detail'),
    url(r'^product/(?P<pk>[0-9]+)/change/$', products.ProductChangeView.as_view(), name='product_change'),
    url(r'^product/(?P<pk>[0-9]+)/delete/$', products.delete_product, name='product_delete'),

    url(r'^announce/$', announces.AnnounceListView.as_view(), name='announce_list'),
    url(r'^announce/new/$', announces.AnnounceAddView.as_view(), name='announce_add'),
    url(r'^announce/(?P<pk>[0-9]+)/change/$', announces.AnnounceChangeView.as_view(), name='announce_change'),
    url(r'^announce/(?P<pk>[0-9]+)/delete/$', announces.delete_announce, name='announce_delete'),

    url(r'^member/$', members.UserListView.as_view(), name='member_list'),
    url(r'^member/new/$', members.UserAddView.as_view(), name='member_add'),
    # url(r'^member/(?P<pk>[0-9]+)/$', members.UserDetailView.as_view(), name='member_detail'),
    url(r'^member/(?P<pk>[0-9]+)/change/$', members.UserChangeView.as_view(), name='member_change'),
    url(r'^member/(?P<pk>[0-9]+)/delete/$', members.delete_user, name='member_delete'),

    url(r'^order/$', orders.OrderListView.as_view(), name='order_list'),
    url(r'^order/payment/$', orders.OrderPaymentView.as_view(), name='payment_list'),
    url(r'^order/payment/(?P<pk>[0-9]+)/(?P<status>[01])/$', orders.confirm_payment, name='payment_update'),
    url(r'^order/(?P<pk>[0-9]+)/$', orders.OrderDetailView.as_view(), name='order_detail'),

    url(r'^article/$', blogs.ArticleListView.as_view(), name='article_list'),
    url(r'^article/new/$', blogs.ArticleAddView.as_view(), name='article_add'),
    url(r'^article/(?P<pk>[0-9]+)/change/$', blogs.ArticleChangeView.as_view(), name='article_change'),
    url(r'^article/(?P<pk>[0-9]+)/delete/$', blogs.delete_article, name='article_delete'),
]

shop/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import views as auth_views

from shop import views
from shop.pages import blogs
from shop.pages import products, carts, checkouts, orders

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', auth_views.login, {'template_name': 'shop/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'shop:index'}, name='logout'),
    url(r'^signup/$', views.Signup.as_view(), name='signup'),
    url(r'^product/$', products.ProductListView.as_view(), name='product_list'),
    url(r'^product/(?P<slug>.+)/$', products.ProductDetailView.as_view(), name='product_detail'),
    url(r'^basket/$', csrf_exempt(carts.CartView.as_view()), name='cart'),
    url(r'^basket/checkout/$', checkouts.CheckoutView.as_view(), name='checkout'),
    url(r'^basket/confirm_order/$', checkouts.ConfirmCheckoutView.as_view(), name='checkout_confirm'),
    url(r'^basket/order/$', orders.OrderView.as_view(), name='order'),
    url(r'^item-count/$', views.item_count, name='item_count'),
    url(r'^payment/bank/$', orders.PaymentView.as_view(), name='payment'),
    url(r'^order/(?P<pk>[0-9]+)/confirm/$', orders.confirm_payment, name='order_confirm'),
    url(r'^order/(?P<pk>[0-9]+)/$', orders.order_detail, name='order_detail'),
    url(r'^basket/confirm_order/update/address/$', checkouts.edit_adress, name='update_address'),
    url(r'^basket/confirm_order/update/delivery/$', checkouts.edit_delivery, name='update_delivery'),
    url(r'^articles/$', blogs.BlogListView.as_view(), name='article_list'),
    url(r'^articles/(?P<slug>.+)/$', blogs.BlogDetailView.as_view(), name='article_detail'),
]

backend/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

backend/forms.py
# encoding=utf8
from __future__ import print_function
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, ReadOnlyPasswordHashField
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

from shop.models import Product, Stock, Gallery, Announce, Member, Article


def change_field_to_bootstrap(fields):
    for field in iter(fields):
        if not isinstance(fields[field].widget, forms.CheckboxInput):
            fields[field].widget.attrs.update({
                'class': 'form-control'
            })

    return fields


class AnnounceModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AnnounceModelForm, self).__init__(*args, **kwargs)
        change_field_to_bootstrap(self.fields)

        self.fields['start'].widget.attrs.update({
            'class': 'form-control date'
        })
        self.fields['end'].widget.attrs.update({
            'class': 'form-control date'
        })

    class Meta:
        model = Announce
        fields = ['name', 'start', 'end', 'image']


class MemberCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(MemberCreationForm, self).__init__(*args, **kwargs)
        change_field_to_bootstrap(self.fields)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'is_staff', 'is_superuser']


class MemberChangeForm(UserChangeForm):
    password = ReadOnlyPasswordHashField(label=("Password"), help_text=("Raw passwords are not stored, so there is no way to see this user's password, but you can change the password using <a class=\"text-primary\" href=\"../password/\">this form</a>."))

    def __init__(self, *args, **kwargs):
        super(MemberChangeForm, self).__init__(*args, **kwargs)
        change_field_to_bootstrap(self.fields)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password', 'email', 'is_staff', 'is_superuser', 'is_active']


class ProductModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProductModelForm, self).__init__(*args, **kwargs)
        change_field_to_bootstrap(self.fields)

    class Meta:
        model = Product
        fields = ['name', 'code', 'brand', 'category', 'color', 'price', 'discount', 'detail', 'image']


class ItemForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ['size', 'total']

    def __init__(self, *args, **kwargs):
        super(ItemForm, self).__init__(*args, **kwargs)
        change_field_to_bootstrap(self.fields)


class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['phone', 'market', 'address', 'province', 'zipcode']

    def __init__(self, *args, **kwargs):
        super(MemberForm, self).__init__(*args, **kwargs)
        change_field_to_bootstrap(self.fields)


class ArticleModelFormAdd(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ArticleModelFormAdd, self).__init__(*args, **kwargs)
        change_field_to_bootstrap(self.fields)

    class Meta:
        model = Article
        fields = ['title', 'detail', 'detail', 'keyword_tags', 'main_image', 'is_active']


class ArticleModelFormChange(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ArticleModelFormChange, self).__init__(*args, **kwargs)
        change_field_to_bootstrap(self.fields)

        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['slug'].widget.attrs['readonly'] = True

    class Meta:
        model = Article
        fields = ['title', 'slug', 'detail', 'detail', 'keyword_tags', 'main_image', 'is_active']


GalleryFormSet = forms.inlineformset_factory(Product, Gallery, fields=['image'], extra=1)
StockFormSet = forms.inlineformset_factory(Product, Stock, fields=['size', 'total'], extra=1, form=ItemForm)
MemberFormSet = forms.inlineformset_factory(User, Member, fields=['phone', 'market', 'address', 'province', 'zipcode'], extra=1, form=MemberForm)

backend/views.py
# encoding=utf8
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import deprecate_current_app
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect
from django.shortcuts import render, resolve_url
from django.template.response import TemplateResponse
from django.utils.http import is_safe_url
from django.views import generic
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters

from backend.mixins import SuperAdminRequiredMixin


class DashboardView(SuperAdminRequiredMixin, generic.View):
    def get(self, request):
        context = {}
        return render(request, "backend/dashboard.html", context)


@deprecate_current_app
@sensitive_post_parameters()
@csrf_protect
@never_cache
def login(request, template_name='backend/login.html',
          redirect_field_name=REDIRECT_FIELD_NAME, authentication_form=AuthenticationForm, extra_context=None):
    """
    Displays the login form and handles the login action.
    """
    redirect_to = request.POST.get(redirect_field_name,
                                   request.GET.get(redirect_field_name, ''))

    if request.method == "POST":
        form = authentication_form(request, data=request.POST)
        if form.is_valid():

            # Ensure the user-originating redirection url is safe.
            if not is_safe_url(url=redirect_to, host=request.get_host()):
                redirect_to = resolve_url('backend:dashboard')

            # Okay, security check complete. Log the user in.
            auth_login(request, form.get_user())

            return HttpResponseRedirect(redirect_to)
    else:
        form = authentication_form(request)

    current_site = get_current_site(request)

    context = {
        'form': form,
        redirect_field_name: redirect_to,
        'site': current_site,
        'site_name': current_site.name,
    }
    if extra_context is not None:
        context.update(extra_context)

    return TemplateResponse(request, template_name, context)

backend/templates/backend/orders/change.html
{% extends 'backend/base.html' %}
{% load staticfiles backend_tags %}

{% block title %}
    แก้ไขสินค้า
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'backend:product_list' %}">สินค้า</a></li>
    <li><a href="{% url 'backend:product_detail' product.id %}">{{ product }}</a></li>
    <li class="active">แก้ไข</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>แก้ไขสินค้า</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <form class="form-horizontal" method="POST" action="{% url 'backend:product_change' product.id %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}" class="col-sm-1 control-label">{{ field.label }}</label>
                            {% for error in field.errors %}
                                <strong>{{ error|escape }}</strong>
                            {% endfor %}
                            <div class="col-sm-11">
                                {% if field.field.widget|klass == 'ClearableFileInput' %}
                                    <p><img src="{{ MEDIA_URL }}{{ field.value }}" alt="" style="height: 60px; width: auto;"></p>
                                {% endif %}
                                {{ field }}
                            </div>
                        </div>
                        {% endfor %}

                        <label class="control-label">Stock Item</label>
                        {{ stock_formset.management_form }}
                        <table class="table">
                            {% for form_set in stock_formset.forms %}
                                <tr {% if forloop.last %}class="formset"{% endif %}>
                                    {% for hidden in form_set.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                    {% for field in form_set.visible_fields %}
                                        <td>
                                            <div class="form-group">
                                                <label for="{{ field.id_for_label }}" class="col-sm-3 control-label">{{ field.label }}: </label>
                                                <div class="col-sm-9">
                                                    {% for error in field.errors %}
                                                        <strong>{{ error|escape }}</strong>
                                                    {% endfor %}
                                                    {{ field }}
                                                </div>
                                            </div>
                                        </td>
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        </table>

                        <label class="control-label">Gallery</label>
                        <legend class="section"></legend>
                        {{ gallery_formset.management_form }}
                        <div class="row">
                            {% for form_set in gallery_formset.forms %}
                                {% if forloop.last %}
                                    <div class="col-md-12">
                                        <table class="table">
                                            <tr class="formset-image">
                                                {% for hidden in form_set.hidden_fields %}
                                                    {{ hidden }}
                                                {% endfor %}
                                                {% for field in form_set.visible_fields %}
                                                    <td>
                                                        <div class="form-group">
                                                            <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}: </label>
                                                            <div class="col-sm-10">
                                                                {% for error in field.errors %}
                                                                    <strong>{{ error|escape }}</strong>
                                                                {% endfor %}
                                                                {{ field }}
                                                            </div>
                                                        </div>
                                                    </td>
                                                {% endfor %}
                                            </tr>
                                        </table>
                                    </div>
                                {% else %}
                                    <div class="col-md-4">
                                        {% for hidden in form_set.hidden_fields %}
                                            {{ hidden }}
                                        {% endfor %}
                                        {% for field in form_set.visible_fields %}
                                            {% if field.field.widget|klass == 'ClearableFileInput' %}
                                                <p><img src="{{ MEDIA_URL }}{{ field.value }}" alt="" style="height: 60px; width: auto;"></p>
                                            {% endif %}
                                            <label for="{{ field.id_for_label }}" class="control-label">{{ field.label }}: </label>
                                            {% for error in field.errors %}
                                                <strong>{{ error|escape }}</strong>
                                            {% endfor %}
                                            {{ field }}
                                        {% endfor %}
                                        <legend class="section"></legend>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                        <div class="text-right">
                            <button type="submit" class="btn btn-info">บันทึก</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_js %}
    <script type="text/javascript">
        var add_txt = '<button class="btn btn-default"><i class="fa fa-plus"> Add Other</button>';
        var remove_txt = '<button class="btn btn-danger"><i class="fa fa-trash"> Remove</button>';
        $('.formset').formset({
            prefix: '{{ stock_formset.prefix }}',
            addText: add_txt,
            deleteText: remove_txt
        });
        $('.formset-image').formset({
            prefix: '{{ gallery_formset.prefix }}',
            addText: add_txt,
            deleteText: remove_txt
        });
    </script>
{% endblock %}

backend/templates/backend/orders/detail.html
{% extends 'backend/base.html' %}
{% load staticfiles table_tags product_tags %}

{% block title %}
    #{{ object.id|stringformat:"06d" }}
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'backend:order_list' %}">การสั่งซื้อ</a></li>
    <li class="active">#{{ object.id|stringformat:"06d" }}</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>หมายเลขคำสั่งซื้อ (Order ID): #{{ object.id|stringformat:"06d" }}</h2>
                    <ul class="nav navbar-right panel_toolbox">

                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-md-4">ราคาสินค้าทั้งหมด</div>
                                <div class="col-md-5">ที่อยู่สำหรับจัดส่งสินค้า</div>
                                <div class="col-md-3">วิธีการจัดส่งสินค้า</div>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <p>ยอดเงินทั้งหมด: <b>{{ object.cart.total }} บาท</b></p>
                                    <p>สถานะ:
                                        {% if object.is_confirm %}
                                            <i class="text-success">ชำระเงินแล้ว</i>
                                        {% else %}
                                            <i class="text-danger">รอการชำระเงิน</i>
                                        {% endif %}
                                    </p>
                                </div>
                                <div class="col-md-5">
                                    <p>{{ object.member.user.first_name }} {{ object.member.user.last_name }}</p>
                                    <p>เบอร์โทรศัพท์ {{ object.member.phone }}</p>
                                    <p>{{ object.member.address }} {{ object.member.province }} {{ object.member.zipcode }}</p>
                                </div>
                                <div class="col-md-3">
                                    <p>จัดส่งแบบ <span style="font-weight: bold;">{{ object.deliver_by|deliver_to_name }}</span></p>
                                    <p>(โดยไปรษณีย์ไทย)</p>
                                </div>
                            </div>

                        </div>
                    </div>

                    <table class="table">
                        <thead>
                        <tr>
                            <th>รายละเอียดคำสั่งซื้อ</th>
                            <th>รายละเอียด</th>
                            <th>จำนวน</th>
                            <th>ราคารวม</th>
                            <th>Comment</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for its in items %}
                            <tr style="height: 65px; line-height: 65px; border-bottom: 1px solid #d7dbe0;">
                                <td style="vertical-align: middle;">
                                    <img src="http://www.aquanineth.com{{ MEDIA_URL }}{{ its.item.product.image }}"
                                         style="vertical-align: bottom; border: 1px solid #ddd; margin-bottom: 4px; width: auto; height: 80px;">
                                </td>
                                <td style="vertical-align: middle;">
                                    {{ its.item.product.name }}<br>
                                    ไซส์: {{ its.item.size|upper }}<br>
                                    ราคา: ฿{{ its.item.product.price }}
                                </td>
                                <td style="vertical-align: middle;">{{ its.quantity }}
                                    ชิ้น
                                </td>
                                <td style="vertical-align: middle;">
                                    ฿{{ its.quantity|item_total_price:its.item.product.price }}</td>
                                <td style="vertical-align: middle;">{{ its.comment }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                    <table style="width: 100%; font-weight: bold; margin-top: 1em; border-spacing: 0; border-collapse: collapse; background-color: transparent;">
                        <tr>
                            <td colspan="2" style="padding: 10px 20px;">ราคารวมของสินค้า</td>
                            <td colspan="2" style="padding-right: 20px; text-align: right;">{{ object.cart.product_total }} บาท
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2" style="padding: 10px 20px;">ค่าจัดส่ง</td>
                            <td colspan="2" style="padding-right: 20px; text-align: right;">{{ object.cart.tax_delivery }} บาท
                            </td>
                        </tr>
                        <tr style="background-color: #EEEEEE">
                            <td colspan="2" style="padding: 10px 20px;"><b>ราคารวมทั้งหมด</b></td>
                            <td colspan="2" style="padding-right: 20px; text-align: right;"><b>{{ object.cart.total }} บาท</b>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

backend/templates/backend/orders/lists.html
{% extends 'backend/base.html' %}
{% load staticfiles table_tags %}

{% block title %}
    รายการสินค้า
{% endblock %}

{% block breadcrumbs %}
    <li class="active">สินค้า</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>รายการสินค้า</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    {% render_table orders %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

backend/templates/backend/orders/new.html
{% extends 'backend/base.html' %}
{% load staticfiles backend_tags %}

{% block title %}
    เพิ่มสินค้าใหม่
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'backend:product_list' %}">สินค้า</a></li>
    <li class="active">ใหม่</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>เพิ่มสินค้าใหม่</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <form class="form-horizontal" method="POST" action="{% url 'backend:product_add' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}" class="col-sm-1 control-label">{{ field.label }}</label>
                            {% for error in field.errors %}
                                <strong>{{ error|escape }}</strong>
                            {% endfor %}
                            <div class="col-sm-11">
                                {{ field }}
                            </div>
                        </div>
                        {% endfor %}

                        <label class="control-label">Stock Item</label>
                        {{ stock_formset.management_form }}
                        <table class="table">
                            {% for form_set in stock_formset.forms %}
                                <tr class="formset">
                                    {% for hidden in form_set.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                    {% for field in form_set.visible_fields %}
                                        <td>
                                            <div class="form-group">
                                                <label for="{{ field.id_for_label }}" class="col-sm-3 control-label">{{ field.label }}: </label>
                                                <div class="col-sm-9">
                                                    {% for error in field.errors %}
                                                        <strong>{{ error|escape }}</strong>
                                                    {% endfor %}
                                                    {{ field }}
                                                </div>
                                            </div>
                                        </td>
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        </table>

                        <label class="control-label">Gallery</label>
                        <legend class="section"></legend>
                        {{ gallery_formset.management_form }}
                        <table class="table">
                            {% for form_set in gallery_formset.forms %}
                                <tr class="formset-image">
                                    {% for hidden in form_set.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                    {% for field in form_set.visible_fields %}
                                        <td>
                                            <div class="form-group">
                                                <label for="{{ field.id_for_label }}" class="col-sm-12 control-label">{{ field.label }}: </label>
                                                <div class="col-sm-10">
                                                    {% for error in field.errors %}
                                                        <strong>{{ error|escape }}</strong>
                                                    {% endfor %}
                                                    {{ field }}
                                                </div>
                                            </div>
                                        </td>
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        </table>
                        <div class="text-right">
                            <button type="submit" class="btn btn-info">บันทึก</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_js %}
    <script type="text/javascript">
        var add_txt = '<button class="btn btn-default"><i class="fa fa-plus"> Add Other</button>';
        var remove_txt = '<button class="btn btn-danger"><i class="fa fa-trash"> Remove</button>';
        $('.formset').formset({
            prefix: '{{ stock_formset.prefix }}',
            addText: add_txt,
            deleteText: remove_txt
        });
        $('.formset-image').formset({
            prefix: '{{ gallery_formset.prefix }}',
            addText: add_txt,
            deleteText: remove_txt
        });
    </script>
{% endblock %}

backend/templates/backend/orders/payment.html
{% extends 'backend/base.html' %}
{% load staticfiles table_tags %}

{% block title %}
    การชำระเงิน
{% endblock %}

{% block breadcrumbs %}
    <li class="active">การชำระเงิน</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>การชำระเงิน</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    {% render_table payments %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}