aquanine/urls.py
from django.conf.urls import url, include, patterns
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('shop.urls', namespace="shop")),
    url(r'^admin/', include('backend.urls', namespace="backend")),
    url(r'^backend/', admin.site.urls),
    url(r'^froala_editor/', include('froala_editor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if DEBUG is True it will be served automatically
if settings.DEBUG is False:
    urlpatterns += patterns('',
            url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
            url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

backend/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from backend import views
from backend.pages import announces
from backend.pages import blogs
from backend.pages import members
from backend.pages import orders

from backend.pages import products

urlpatterns = [
    # url('^',include('django.contrib.auth.urls')),
    url(r'^$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'backend:login'}, name='logout'),
    url(r'^product/$', products.ProductListView.as_view(), name='product_list'),
    url(r'^product/new/$', products.ProductAddView.as_view(), name='product_add'),
    url(r'^product/(?P<pk>[0-9]+)/$', products.ProductDetailView.as_view(), name='product_detail'),
    url(r'^product/(?P<pk>[0-9]+)/change/$', products.ProductChangeView.as_view(), name='product_change'),
    url(r'^product/(?P<pk>[0-9]+)/delete/$', products.delete_product, name='product_delete'),

    url(r'^announce/$', announces.AnnounceListView.as_view(), name='announce_list'),
    url(r'^announce/new/$', announces.AnnounceAddView.as_view(), name='announce_add'),
    url(r'^announce/(?P<pk>[0-9]+)/change/$', announces.AnnounceChangeView.as_view(), name='announce_change'),
    url(r'^announce/(?P<pk>[0-9]+)/delete/$', announces.delete_announce, name='announce_delete'),

    url(r'^member/$', members.UserListView.as_view(), name='member_list'),
    url(r'^member/new/$', members.UserAddView.as_view(), name='member_add'),
    # url(r'^member/(?P<pk>[0-9]+)/$', members.UserDetailView.as_view(), name='member_detail'),
    url(r'^member/(?P<pk>[0-9]+)/change/$', members.UserChangeView.as_view(), name='member_change'),
    url(r'^member/(?P<pk>[0-9]+)/delete/$', members.delete_user, name='member_delete'),

    url(r'^order/$', orders.OrderListView.as_view(), name='order_list'),
    url(r'^order/payment/$', orders.OrderPaymentView.as_view(), name='payment_list'),
    url(r'^order/payment/(?P<pk>[0-9]+)/(?P<status>[01])/$', orders.confirm_payment, name='payment_update'),
    url(r'^order/(?P<pk>[0-9]+)/$', orders.OrderDetailView.as_view(), name='order_detail'),

    url(r'^article/$', blogs.ArticleListView.as_view(), name='article_list'),
    url(r'^article/new/$', blogs.ArticleAddView.as_view(), name='article_add'),
    url(r'^article/(?P<pk>[0-9]+)/change/$', blogs.ArticleChangeView.as_view(), name='article_change'),
    url(r'^article/(?P<pk>[0-9]+)/delete/$', blogs.delete_article, name='article_delete'),
]

shop/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import views as auth_views

from shop import views
from shop.pages import blogs
from shop.pages import products, carts, checkouts, orders

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', auth_views.login, {'template_name': 'shop/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'shop:index'}, name='logout'),
    url(r'^signup/$', views.Signup.as_view(), name='signup'),
    url(r'^product/$', products.ProductListView.as_view(), name='product_list'),
    url(r'^product/(?P<slug>.+)/$', products.ProductDetailView.as_view(), name='product_detail'),
    url(r'^basket/$', csrf_exempt(carts.CartView.as_view()), name='cart'),
    url(r'^basket/checkout/$', checkouts.CheckoutView.as_view(), name='checkout'),
    url(r'^basket/confirm_order/$', checkouts.ConfirmCheckoutView.as_view(), name='checkout_confirm'),
    url(r'^basket/order/$', orders.OrderView.as_view(), name='order'),
    url(r'^item-count/$', views.item_count, name='item_count'),
    url(r'^payment/bank/$', orders.PaymentView.as_view(), name='payment'),
    url(r'^order/(?P<pk>[0-9]+)/confirm/$', orders.confirm_payment, name='order_confirm'),
    url(r'^order/(?P<pk>[0-9]+)/$', orders.order_detail, name='order_detail'),
    url(r'^basket/confirm_order/update/address/$', checkouts.edit_adress, name='update_address'),
    url(r'^basket/confirm_order/update/delivery/$', checkouts.edit_delivery, name='update_delivery'),
    url(r'^articles/$', blogs.BlogListView.as_view(), name='article_list'),
    url(r'^articles/(?P<slug>.+)/$', blogs.BlogDetailView.as_view(), name='article_detail'),
]

backend/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

backend/forms.py
# encoding=utf8
from __future__ import print_function
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, ReadOnlyPasswordHashField
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

from shop.models import Product, Stock, Gallery, Announce, Member, Article


def change_field_to_bootstrap(fields):
    for field in iter(fields):
        if not isinstance(fields[field].widget, forms.CheckboxInput):
            fields[field].widget.attrs.update({
                'class': 'form-control'
            })

    return fields


class AnnounceModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AnnounceModelForm, self).__init__(*args, **kwargs)
        change_field_to_bootstrap(self.fields)

        self.fields['start'].widget.attrs.update({
            'class': 'form-control date'
        })
        self.fields['end'].widget.attrs.update({
            'class': 'form-control date'
        })

    class Meta:
        model = Announce
        fields = ['name', 'start', 'end', 'image']


class MemberCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(MemberCreationForm, self).__init__(*args, **kwargs)
        change_field_to_bootstrap(self.fields)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'is_staff', 'is_superuser']


class MemberChangeForm(UserChangeForm):
    password = ReadOnlyPasswordHashField(label=("Password"), help_text=("Raw passwords are not stored, so there is no way to see this user's password, but you can change the password using <a class=\"text-primary\" href=\"../password/\">this form</a>."))

    def __init__(self, *args, **kwargs):
        super(MemberChangeForm, self).__init__(*args, **kwargs)
        change_field_to_bootstrap(self.fields)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password', 'email', 'is_staff', 'is_superuser', 'is_active']


class ProductModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProductModelForm, self).__init__(*args, **kwargs)
        change_field_to_bootstrap(self.fields)

    class Meta:
        model = Product
        fields = ['name', 'code', 'brand', 'category', 'color', 'price', 'discount', 'detail', 'image']


class ItemForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ['size', 'total']

    def __init__(self, *args, **kwargs):
        super(ItemForm, self).__init__(*args, **kwargs)
        change_field_to_bootstrap(self.fields)


class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['phone', 'market', 'address', 'province', 'zipcode']

    def __init__(self, *args, **kwargs):
        super(MemberForm, self).__init__(*args, **kwargs)
        change_field_to_bootstrap(self.fields)


class ArticleModelFormAdd(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ArticleModelFormAdd, self).__init__(*args, **kwargs)
        change_field_to_bootstrap(self.fields)

    class Meta:
        model = Article
        fields = ['title', 'detail', 'detail', 'keyword_tags', 'main_image', 'is_active']


class ArticleModelFormChange(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ArticleModelFormChange, self).__init__(*args, **kwargs)
        change_field_to_bootstrap(self.fields)

        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['slug'].widget.attrs['readonly'] = True

    class Meta:
        model = Article
        fields = ['title', 'slug', 'detail', 'detail', 'keyword_tags', 'main_image', 'is_active']


GalleryFormSet = forms.inlineformset_factory(Product, Gallery, fields=['image'], extra=1)
StockFormSet = forms.inlineformset_factory(Product, Stock, fields=['size', 'total'], extra=1, form=ItemForm)
MemberFormSet = forms.inlineformset_factory(User, Member, fields=['phone', 'market', 'address', 'province', 'zipcode'], extra=1, form=MemberForm)

backend/views.py
# encoding=utf8
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import deprecate_current_app
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect
from django.shortcuts import render, resolve_url
from django.template.response import TemplateResponse
from django.utils.http import is_safe_url
from django.views import generic
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters

from backend.mixins import SuperAdminRequiredMixin


class DashboardView(SuperAdminRequiredMixin, generic.View):
    def get(self, request):
        context = {}
        return render(request, "backend/dashboard.html", context)


@deprecate_current_app
@sensitive_post_parameters()
@csrf_protect
@never_cache
def login(request, template_name='backend/login.html',
          redirect_field_name=REDIRECT_FIELD_NAME, authentication_form=AuthenticationForm, extra_context=None):
    """
    Displays the login form and handles the login action.
    """
    redirect_to = request.POST.get(redirect_field_name,
                                   request.GET.get(redirect_field_name, ''))

    if request.method == "POST":
        form = authentication_form(request, data=request.POST)
        if form.is_valid():

            # Ensure the user-originating redirection url is safe.
            if not is_safe_url(url=redirect_to, host=request.get_host()):
                redirect_to = resolve_url('backend:dashboard')

            # Okay, security check complete. Log the user in.
            auth_login(request, form.get_user())

            return HttpResponseRedirect(redirect_to)
    else:
        form = authentication_form(request)

    current_site = get_current_site(request)

    context = {
        'form': form,
        redirect_field_name: redirect_to,
        'site': current_site,
        'site_name': current_site.name,
    }
    if extra_context is not None:
        context.update(extra_context)

    return TemplateResponse(request, template_name, context)

backend/templates/backend/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>ระบบหลังร้าน | {% block title %}{% endblock %}</title>

    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/gentelella/build/css/custom.min.css' %}" rel="stylesheet">
    <!-- Vendor Section -->
    <link href="{% static 'froala_editor/css/froala_editor.min.css' %}" rel="stylesheet">
    <link href="{% static 'froala_editor/css/froala_style.min.css' %}" rel="stylesheet">
    <link href="{% static 'froala_editor/css/froala-django.css' %}" rel="stylesheet">
    <link href="{% static 'froala_editor/css/plugins/char_counter.min.css' %}" rel="stylesheet">
    <link href="{% static 'froala_editor/css/plugins/code_view.min.css' %}" rel="stylesheet">
    <link href="{% static 'froala_editor/css/plugins/colors.min.css' %}" rel="stylesheet">
    <link href="{% static 'froala_editor/css/plugins/emoticons.min.css' %}" rel="stylesheet">
    <link href="{% static 'froala_editor/css/plugins/file.min.css' %}" rel="stylesheet">
    <link href="{% static 'froala_editor/css/plugins/fullscreen.min.css' %}" rel="stylesheet">
    <link href="{% static 'froala_editor/css/plugins/image.min.css' %}" rel="stylesheet">
    <link href="{% static 'froala_editor/css/plugins/image_manager.min.css' %}" rel="stylesheet">
    <link href="{% static 'froala_editor/css/plugins/line_breaker.min.css' %}" rel="stylesheet">
    <link href="{% static 'froala_editor/css/plugins/table.min.css' %}" rel="stylesheet">
    <link href="{% static 'froala_editor/css/plugins/video.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/bootstrap-multiselect/dist/css/bootstrap-multiselect.css' %}"  rel="stylesheet">
    <link href="{% static 'vendors/gentelella/vendors/pnotify/dist/pnotify.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/ekko-lightbox/dist/ekko-lightbox.min.css' %}" rel="stylesheet">
    {% block custom_css %}{% endblock %}

    <script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
</head>

<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col menu_fixed">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="{% url 'backend:dashboard' %}" class="site_title"><i class="fa fa-shopping-cart"></i> <span>ระบบจัดการ</span></a>
                    </div>
                    <div class="clearfix"></div>
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        {% include 'backend/left_menu.html' %}
                    </div>
                </div>
            </div>

            <div class="top_nav">
                <div class="nav_menu">
                    <nav class="" role="navigation">
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>

                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    {{ request.user.username }} <span class=" fa fa-angle-down"></span>
                                </a>
                                <ul class="dropdown-menu dropdown-usermenu pull-right">
                                    <li><a href="javascript:;"><i class="fa fa-user pull-right"></i> Profile</a></li>
                                    <li><a href="javascript:;"><i class="fa fa-lock pull-right"></i> Change Password</a></li>
                                    <li><a href="{% url 'backend:logout' %}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                                </ul>
                            </li>

{#                            <li role="presentation" class="dropdown">#}
{#                                <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">#}
{#                                    <i class="fa fa-envelope-o"></i>#}
{#                                    <span class="badge bg-green">1</span>#}
{#                                </a>#}
{#                                <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">#}
{#                                    <li>#}
{#                                        <a>#}
{#                                            <span>John Smith</span>#}
{#                                            <span class="time">3 mins ago</span>#}
{#                                            <span class="message">#}
{#                                                Film festivals used to be do-or-die moments for movie makers. They were where...#}
{#                                            </span>#}
{#                                        </a>#}
{#                                    </li>#}
{#                                    <li>#}
{#                                        <div class="text-center">#}
{#                                            <a>#}
{#                                                <strong>See All Alerts</strong>#}
{#                                                <i class="fa fa-angle-right"></i>#}
{#                                            </a>#}
{#                                        </div>#}
{#                                    </li>#}
{#                                </ul>#}
{#                            </li>#}
                        </ul>
                    </nav>
                </div>
            </div>

            <!-- page content -->
            <div class="right_col" role="main">
                <div class="page-title">
                    <div class="title_left">
                        <ol class="breadcrumb">
                            <li><a href="{% url 'backend:dashboard' %}">ระบบจัดการ</a></li>
                            {% block breadcrumbs %}{% endblock %}
                        </ol>

                    </div>
                </div>

                <div class="clearfix"></div>
                {% block content %}{% endblock %}
            </div>
            <!-- /page content -->

            <!-- footer content -->
            <footer>
                <div class="pull-right">
                    Copyright &reg; 2016, <a href="http://www.aquanineth.com">Aquanine Brand</a> All right Reserved.
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>

    <script src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendors/fastclick/lib/fastclick.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendors/nprogress/nprogress.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendors/gentelella/build/js/custom.min.js' %}" type="text/javascript"></script>
    <!-- Vendor Section -->
    <script src="{% static 'froala_editor/js/froala_editor.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/froala-django.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/align.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/char_counter.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/code_beautifier.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/code_view.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/colors.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/emoticons.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/entities.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/file.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/font_family.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/font_size.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/fullscreen.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/image.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/image_manager.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/inline_style.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/line_breaker.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/link.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/lists.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/paragraph_format.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/paragraph_style.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/quote.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/save.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/table.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/url.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'froala_editor/js/plugins/video.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendors/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap-multiselect/dist/js/bootstrap-multiselect.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendors/gentelella/vendors/pnotify/dist/pnotify.js' %}"></script>
    <script src="{% static 'vendors/ekko-lightbox/dist/ekko-lightbox.min.js' %}"></script>

    <script src="{% static 'js/jquery.formset.js' %}" type="text/javascript"></script>
    {% block include_js %}{% endblock %}

    <script type="text/javascript">
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                notify({{ error }}, 'error');
            {% endfor %}
        {% endif %}

        $(document).on('click', '[data-toggle="lightbox"]', function(event) {
            event.preventDefault();
            $(this).ekkoLightbox();
        });

        $(document).ready(function () {
            $('.date').datepicker({
                format: "yyyy-mm-dd",
                todayBtn: "linked",
                autoclose: true,
                todayHighlight: true
            });
        });

        function notify(message, type) {
            var stack_bottomright = {"dir1": "up", "dir2": "left", "push": "bottom"};
            var opts = {
                title: "Notification",
                text: message,
                styling: 'bootstrap3',
                addclass: "stack-bottomright",
                stack: stack_bottomright
            };
            switch (type) {
                case 'error':
                    opts.title = "Error!";
                    opts.type = "error";
                    break;
                case 'info':
                    opts.title = "Alert Notification";
                    opts.type = "info";
                    break;
                case 'success':
                    opts.title = "Success!";
                    opts.type = "success";
                    break;
            }
            new PNotify(opts);
        }
    </script>
    {% block custom_js %}{% endblock %}
</body>
</html>

backend/templates/backend/dashboard.html
{% extends 'backend/base.html' %}
{% load staticfiles %}

{% block title %}
    Dashboard
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Plain Page</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Settings 1</a>
                                </li>
                                <li><a href="#">Settings 2</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    Add content to the page ...
                </div>
            </div>
        </div>
    </div>
{% endblock %}

backend/templates/backend/left_menu.html
<div class="menu_section">
    <ul class="nav side-menu">
        <li><a href="{% url 'shop:index' %}"><i class="fa fa-home"></i> หน้าร้านค้า</a></li>
        <li><a href="{% url 'backend:dashboard' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a><i class="fa fa-bullhorn"></i> ประกาศ <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
                <li><a href="{% url 'backend:announce_list' %}">รายการประกาศ</a></li>
                <li><a href="{% url 'backend:announce_add' %}">เพิ่มประกาศใหม่</a></li>
            </ul>
        </li>
        <li><a><i class="fa fa-shopping-cart"></i> Order <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
                <li><a href="{% url 'backend:order_list' %}">รายการ Order</a></li>
                <li><a href="{% url 'backend:payment_list' %}">การแจ้งชำระเงิน</a></li>
            </ul>
        </li>
        <li><a><i class="fa fa-shopping-basket"></i> สินค้า <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
                <li><a href="{% url 'backend:product_list' %}">รายการสินค้า</a></li>
                <li><a href="{% url 'backend:product_add' %}">เพิ่มสินค้าใหม่</a></li>
            </ul>
        </li>
        <li><a><i class="fa fa-wordpress"></i> บทความ <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
                <li><a href="{% url 'backend:article_list' %}">รายชื่อบทความ</a></li>
                <li><a href="{% url 'backend:article_add' %}">เพิ่มบทความใหม่</a></li>
            </ul>
        </li>
        <li><a><i class="fa fa-user"></i> สมาชิก/ลูกค้า <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
                <li><a href="{% url 'backend:member_list' %}">รายชื่อสมาชิก</a></li>
                <li><a href="{% url 'backend:member_add' %}">เพิ่มสมาชิกใหม่</a></li>
            </ul>
        </li>
        <li><a href="{% url 'backend:logout' %}"><i class="fa fa-sign-out"></i> ออกจากระบบ</a></li>
    </ul>
</div>