aquanine/urls.py
from django.conf.urls import url, include, patterns
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('shop.urls', namespace="shop")),
    url(r'^admin/', include('backend.urls', namespace="backend")),
    url(r'^backend/', admin.site.urls),
    url(r'^froala_editor/', include('froala_editor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if DEBUG is True it will be served automatically
if settings.DEBUG is False:
    urlpatterns += patterns('',
            url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
            url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

backend/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from backend import views
from backend.pages import announces
from backend.pages import blogs
from backend.pages import members
from backend.pages import orders

from backend.pages import products

urlpatterns = [
    # url('^',include('django.contrib.auth.urls')),
    url(r'^$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'backend:login'}, name='logout'),
    url(r'^product/$', products.ProductListView.as_view(), name='product_list'),
    url(r'^product/new/$', products.ProductAddView.as_view(), name='product_add'),
    url(r'^product/(?P<pk>[0-9]+)/$', products.ProductDetailView.as_view(), name='product_detail'),
    url(r'^product/(?P<pk>[0-9]+)/change/$', products.ProductChangeView.as_view(), name='product_change'),
    url(r'^product/(?P<pk>[0-9]+)/delete/$', products.delete_product, name='product_delete'),

    url(r'^announce/$', announces.AnnounceListView.as_view(), name='announce_list'),
    url(r'^announce/new/$', announces.AnnounceAddView.as_view(), name='announce_add'),
    url(r'^announce/(?P<pk>[0-9]+)/change/$', announces.AnnounceChangeView.as_view(), name='announce_change'),
    url(r'^announce/(?P<pk>[0-9]+)/delete/$', announces.delete_announce, name='announce_delete'),

    url(r'^member/$', members.UserListView.as_view(), name='member_list'),
    url(r'^member/new/$', members.UserAddView.as_view(), name='member_add'),
    # url(r'^member/(?P<pk>[0-9]+)/$', members.UserDetailView.as_view(), name='member_detail'),
    url(r'^member/(?P<pk>[0-9]+)/change/$', members.UserChangeView.as_view(), name='member_change'),
    url(r'^member/(?P<pk>[0-9]+)/delete/$', members.delete_user, name='member_delete'),

    url(r'^order/$', orders.OrderListView.as_view(), name='order_list'),
    url(r'^order/payment/$', orders.OrderPaymentView.as_view(), name='payment_list'),
    url(r'^order/payment/(?P<pk>[0-9]+)/(?P<status>[01])/$', orders.confirm_payment, name='payment_update'),
    url(r'^order/(?P<pk>[0-9]+)/$', orders.OrderDetailView.as_view(), name='order_detail'),

    url(r'^article/$', blogs.ArticleListView.as_view(), name='article_list'),
    url(r'^article/new/$', blogs.ArticleAddView.as_view(), name='article_add'),
    url(r'^article/(?P<pk>[0-9]+)/change/$', blogs.ArticleChangeView.as_view(), name='article_change'),
    url(r'^article/(?P<pk>[0-9]+)/delete/$', blogs.delete_article, name='article_delete'),
]

shop/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import views as auth_views

from shop import views
from shop.pages import blogs
from shop.pages import products, carts, checkouts, orders

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', auth_views.login, {'template_name': 'shop/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'shop:index'}, name='logout'),
    url(r'^signup/$', views.Signup.as_view(), name='signup'),
    url(r'^product/$', products.ProductListView.as_view(), name='product_list'),
    url(r'^product/(?P<slug>.+)/$', products.ProductDetailView.as_view(), name='product_detail'),
    url(r'^basket/$', csrf_exempt(carts.CartView.as_view()), name='cart'),
    url(r'^basket/checkout/$', checkouts.CheckoutView.as_view(), name='checkout'),
    url(r'^basket/confirm_order/$', checkouts.ConfirmCheckoutView.as_view(), name='checkout_confirm'),
    url(r'^basket/order/$', orders.OrderView.as_view(), name='order'),
    url(r'^item-count/$', views.item_count, name='item_count'),
    url(r'^payment/bank/$', orders.PaymentView.as_view(), name='payment'),
    url(r'^order/(?P<pk>[0-9]+)/confirm/$', orders.confirm_payment, name='order_confirm'),
    url(r'^order/(?P<pk>[0-9]+)/$', orders.order_detail, name='order_detail'),
    url(r'^basket/confirm_order/update/address/$', checkouts.edit_adress, name='update_address'),
    url(r'^basket/confirm_order/update/delivery/$', checkouts.edit_delivery, name='update_delivery'),
    url(r'^articles/$', blogs.BlogListView.as_view(), name='article_list'),
    url(r'^articles/(?P<slug>.+)/$', blogs.BlogDetailView.as_view(), name='article_detail'),
]

shop/models.py
# encoding=utf8
import hashlib

from django.core.validators import RegexValidator, MinLengthValidator
from django.utils.encoding import python_2_unicode_compatible

import os

from django.db import models
from datetime import datetime, date, timedelta
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from froala_editor.fields import FroalaField

from django.utils.text import slugify

TODAY = date.today()
YESTERDAY = (TODAY - timedelta(1))
LAST2DAY = (TODAY - timedelta(2))

month_lists = ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน',
               'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม']

size_choice = (('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'))
colours_choice = (
    ('White', 'ขาว'), ('Black', 'ดำ'), ('Red', 'แดง'), ('Blue', 'น้ำเงิน'), ('Navy Blue', 'กรม'),
    ('Top Black', 'ท้อปดำ'),
    ('Top Gray', 'ท้อปเทา'), ('Black/Black', 'ดำ/ดำ'), ('Black/Red', 'ดำ/แดง'))
provinces_choice = (
    (u"กรุงเทพมหานคร", "กรุงเทพมหานคร"), (u"กระบี่", "กระบี่"), (u"กาญจนบุรี", "กาญจนบุรี"),
    (u"กาฬสินธุ์", "กาฬสินธุ์"),
    (u"กำแพงเพชร", "กำแพงเพชร"), (u"ขอนแก่น", "ขอนแก่น"), (u"จันทบุรี", "ขอนแก่น"), (u"ฉะเชิงเทรา", "ฉะเชิงเทรา"),
    (u"ชลบุรี", "ชลบุรี"), (u"ชัยนาท", "ชัยนาท"), (u"ชัยภูมิ", "ชัยภูมิ"), (u"ชุมพร", "ชุมพร"),
    (u"เชียงราย", "เชียงราย"),
    (u"เชียงใหม่", "เชียงใหม่"), (u"ตรัง", "ตรัง"), (u"ตราด", "ตราด"), (u"ตาก", "ตาก"), (u"นครนายก", "นครนายก"),
    (u"นครปฐม", "นครปฐม"), (u"นครพนม", "นครพนม"), (u"นครราชสีมา", "นครราชสีมา"), (u"นครศรีธรรมราช", "นครศรีธรรมราช"),
    (u"นครสวรรค์", "นครสวรรค์"), (u"นนทบุรี", "นนทบุรี"), (u"นราธิวาส", "นราธิวาส"), (u"น่าน", "น่าน"),
    (u"บุรีรัมย์", "บุรีรัมย์"), (u"บึงกาฬ", "บึงกาฬ"), (u"ปทุมธานี", "ปทุมธานี"),
    (u"ประจวบคีรีขันธ์", "ประจวบคีรีขันธ์"),
    (u"ปราจีนบุรี", "ปราจีนบุรี"), (u"ปัตตานี", "ปัตตานี"), (u"พระนครศรีอยุธยา", "พระนครศรีอยุธยา"),
    (u"พะเยา", "พะเยา"),
    (u"พังงา", "พังงา"), (u"พัทลุง", "พัทลุง"), (u"พิจิตร", "พิจิตร"), (u"พิษณุโลก", "พิษณุโลก"),
    (u"เพชรบุรี", "เพชรบุรี"),
    (u"เพชรบูรณ์", "เพชรบูรณ์"), (u"แพร่", "แพร่"), (u"ภูเก็ต", "ภูเก็ต"), (u"มหาสารคาม", "มหาสารคาม"),
    (u"มุกดาหาร", "มุกดาหาร"), (u"แม่ฮ่องสอน", "แม่ฮ่องสอน"), (u"ยโสธร", "ยโสธร"), (u"ยะลา", "ยะลา"),
    (u"ร้อยเอ็ด", "ร้อยเอ็ด"), (u"ระนอง", "ระนอง"), (u"ระยอง", "ระยอง"), (u"ราชบุรี", "ราชบุรี"), (u"ลพบุรี", "ลพบุรี"),
    (u"ลำปาง", "ลำปาง"), (u"ลำพูน", "ลำพูน"), (u"เลย", "เลย"), (u"ศรีสะเกษ", "ศรีสะเกษ"), (u"สกลนคร", "สกลนคร"),
    (u"สงขลา", "สงขลา"), (u"สตูล", "สตูล"), (u"สมุทรปราการ", "สมุทรปราการ"), (u"สมุทรสงคราม", "สมุทรสงคราม"),
    (u"สมุทรสาคร", "สมุทรสาคร"), (u"สระแก้ว", "สระแก้ว"), (u"สระบุรี", "สระบุรี"), (u"สิงห์บุรี", "สิงห์บุรี"),
    (u"สุโขทัย", "สุโขทัย"), (u"สุพรรณบุรี", "สุพรรณบุรี"), (u"สุราษฎร์ธานี", "สุราษฎร์ธานี"),
    (u"สุรินทร์", "สุรินทร์"),
    (u"หนองคาย", "หนองคาย"), (u"หนองบัวลำภู", "หนองบัวลำภู"), (u"อ่างทอง", "อ่างทอง"), (u"อำนาจเจริญ", "อำนาจเจริญ"),
    (u"อุดรธานี", "อุดรธานี"), (u"อุตรดิตถ์", "อุตรดิตถ์"), (u"อุทัยธานี", "อุทัยธานี"),
    (u"อุบลราชธานี", "อุบลราชธานี"))

pays_choice = (('bank', 'โอนเงินเข้าบัญชีธนาคาร (ที่สาขา, ตู้ ATM หรือ ออนไลน์)'),)
deliveries_choice = (('normal', 'ธรรมดาแบบลงทะเบียน 2-10 วัน (30 บาท)'), ('ems', 'EMS ด่วนพิเศษ 1-2 วัน (50 บาท)'))
bank_choice = (('', 'กรุณาเลือกธนาคาร'), ('scb', 'ธนาคารไทยพาณิชย์'), ('kbank', 'ธนาคารกสิกรไทย'))
last2day_choice = (('', 'กรุณาเลือกวันที่'), (TODAY, '{0} {1}'.format(TODAY.day, month_lists[TODAY.month - 1])),
                   (YESTERDAY, '{0} {1}'.format(YESTERDAY.day, month_lists[YESTERDAY.month - 1])),
                   (LAST2DAY, '{0} {1}'.format(LAST2DAY.day, month_lists[LAST2DAY.month - 1])))


def validate_image_extension(value):
    ext = os.path.splitext(value.name)[1]
    valid_extensions = ['.png', '.jpg', '.jpeg']
    if not ext.lower() in valid_extensions:
        raise ValidationError('File is not Allowed!')
    return value


def create_hash(url):
    hash = hashlib.sha1()
    hash.update(url)
    return hash.hexdigest()[:-10]


def new_filename(filename):
    extension = filename.split('.')[-1]
    filename_hash = create_hash(filename)
    subdir1 = filename_hash[-3:]
    subdir2 = filename_hash[-6:-3]
    new_filename = '{0}.{1}'.format(filename_hash, extension)
    fullpath_file = os.path.join(subdir1, subdir2, new_filename)
    return fullpath_file


def upload_file(instance, filename):
    full_path = new_filename(filename)
    return full_path


def upload_to_file(instance, filename):
    full_path = new_filename(filename)
    return u'announces/{0}'.format(full_path)


def slip_upload(instance, filename):
    full_path = new_filename(filename)
    return u'slips/{0}'.format(full_path)


def product_upload(instance, filename):
    full_path = new_filename(filename)
    return u'products/{0}'.format(full_path)


def product_upload_to_gallery(instance, filename):
    full_path = new_filename(filename)
    return u'products/{0}'.format(full_path)


@python_2_unicode_compatible
class Member(models.Model):
    user = models.OneToOneField(User)
    phone = models.CharField(max_length=20, blank=True)
    market = models.CharField(max_length=255, blank=True)
    address = models.TextField(blank=True)
    province = models.CharField(max_length=100, choices=provinces_choice, blank=True, null=True)
    zipcode = models.CharField(max_length=5, blank=True,
                               validators=[RegexValidator(r'^\d{1,5}$'), MinLengthValidator(4)])

    def __str__(self):
        return self.user.get_full_name()

    def get_full_address(self):
        return u'{0} {1} {2} {3}'.format(self.market, self.address, self.province, self.zipcode)


@python_2_unicode_compatible
class Announce(models.Model):
    name = models.CharField(max_length=255)
    start = models.DateField(default=date.today)
    end = models.DateField(blank=True, null=True)
    image = models.FileField(upload_to=upload_to_file, validators=[validate_image_extension])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Brand(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Colour(models.Model):
    name_th = models.CharField(max_length=80, blank=True)
    name_en = models.CharField(max_length=80, blank=True)

    def __str__(self):
        return u'{0} ({1})'.format(self.name_th, self.name_en)


@python_2_unicode_compatible
class Product(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=255, unique=True)
    brand = models.ForeignKey(Brand, blank=True, null=True)
    category = models.ForeignKey(Category, blank=True, null=True)
    color = models.ForeignKey(Colour, blank=True, null=True)
    price = models.DecimalField(default=0, max_digits=6, decimal_places=2)
    discount = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    detail = FroalaField(blank=True, options={'heightMin': 250})
    slug = models.SlugField(allow_unicode=True)
    image = models.FileField(upload_to=product_upload, validators=[validate_image_extension])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return u'{} - {}'.format(self.name, self.code)

    def discount_percent(self):
        return u'{}%'.format(int((1 - (self.discount / self.price)) * 100))


@python_2_unicode_compatible
class Gallery(models.Model):
    image = models.FileField(upload_to=product_upload_to_gallery, validators=[validate_image_extension])
    product = models.ForeignKey(Product)

    def __str__(self):
        return str(self.id)


@python_2_unicode_compatible
class Stock(models.Model):
    name = models.CharField(max_length=255, blank=True)
    size = models.CharField(max_length=255, choices=size_choice)
    total = models.IntegerField(default=0)
    product = models.ForeignKey(Product)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return u'{} ({})'.format(self.size, self.total)


@python_2_unicode_compatible
class CartItem(models.Model):
    cart = models.ForeignKey("Cart")
    item = models.ForeignKey(Stock)
    quantity = models.PositiveIntegerField(default=1)
    comment = models.CharField(max_length=255, default='-')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return u'{} - {}'.format(self.item.product.name, self.item.product.code)


@python_2_unicode_compatible
class Cart(models.Model):
    member = models.ForeignKey(Member, blank=True, null=True)
    items = models.ManyToManyField(Stock, through=CartItem)
    total = models.DecimalField(max_digits=50, decimal_places=2, default=0)
    product_total = models.DecimalField(max_digits=50, decimal_places=2, default=0)
    tax_delivery = models.DecimalField(max_digits=50, decimal_places=2, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.id)


@python_2_unicode_compatible
class Order(models.Model):
    member = models.ForeignKey(Member)
    cart = models.OneToOneField(Cart)
    pay_by = models.CharField(max_length=255, choices=pays_choice, blank=True, null=True)
    deliver_by = models.CharField(max_length=255, choices=deliveries_choice, blank=True, null=True)
    is_confirm = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

shop/templates/shop/blog_list.html
{% extends "shop/base.html" %}
{% load staticfiles %}

{% block title %}
    บทความ
{% endblock %}

{% block main_content %}
    <div class="login">
        <div class="wrap">
            <h4 class="title">บทความจากทาง Aquanine TH</h4>
            <hr>
            <div class="comments-area">
                {% if object_list %}
                    {% for object in object_list %}
                        <div class="labout span_1_of_a1">
                            <img src="{{ MEDIA_URL }}{{ object.main_image }}" style="width: 100%; height: auto;">
                        </div>
                        <div class="cont1 span_2_of_a1">
                            <p style="font-weight: bold;">{{ object.title }}</p>
                            <p>{{ object.detail|safe|striptags|truncatewords_html:120 }} <a href="{% url 'shop:article_detail' object.slug %}">อ่านต่อ</a></p>
                        </div>
                        <div class="clear"></div>
                        <hr>
                    {% endfor %}

                    {% if is_paginated %}
                        <div class="pagination" style="text-align: center; margin-top: 1.5em;">
                            <span class="page-links">
                                {% if page_obj.has_previous %}
                                    <a href="{% url 'shop:article_list' %}?page={{ page_obj.previous_page_number }}" class="btn">ย้อนกลับ</a>
                                {% endif %}
                                {% if page_obj.has_next %}
                                    <a href="{% url 'shop:article_list' %}?page={{ page_obj.next_page_number }}" class="btn">หน้าต่อไป</a>
                                {% endif %}
                            </span>
                        </div>
                    {% endif %}
                {% else %}
                    <p>ยังไม่มีบทความใหม่ในขณะนี้</p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="clear"></div>
{% endblock %}

shop/templates/shop/confirm_order.html
{% extends "shop/base.html" %}
{% load staticfiles product_tags %}

{% block title %}
    Check Out
{% endblock %}

{% block main_content %}
    <div class="login">
        <div class="wrap">
            <table class="table table-border">
                <thead>
                <tr>
                    <th>ที่อยู่จัดส่งสินค้า</th>
                    <th>วิธีการจัดส่งสินค้า</th>
                    <th>คูปองและ Point</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <p>{{ request.session.first_name }} {{ request.session.last_name }}</p>
                        <p>{{ request.session.address }}</p>
                        <p style="margin-bottom: 10px;">{{ request.session.province }} {{ request.session.zipcode }}</p>
                        <p>
                            <button class="btn" onclick="editAddress();">แก้ไขข้อมูล</button>
                        </p>
                    </td>
                    <td>
                        <p>จัดส่งแบบ <span
                                style="font-weight: bold;">{{ request.session.deliver_by|deliver_to_name }}</span></p>
                        <p style="margin-bottom: 10px;">(โดยไปรษณีย์ไทย)</p>
                        {% if request.session.deliver_by != 'ems' or cart.tax_delivery != 0 %}
                            <p>
                                <button class="btn" onclick="editDelivery();">แก้ไขข้อมูล</button>
                            </p>
                        {% endif %}
                    </td>
                    <td>ถ้าคุณมีคูปอง <a href="{% url 'shop:cart' %}">สามารถใช้ได้ที่หน้า basket</a></td>
                </tr>
                </tbody>
            </table>

            <table id="cart" class="table">
                <thead>
                <tr>
                    <th>รูปสินค้า</th>
                    <th>รหัสสินค้า</th>
                    <th>ชื่อสินค้า</th>
                    <th>ขนาด</th>
                    <th>ราคาสินค้า</th>
                    <th>จำนวน</th>
                    <th>ราคารวม</th>
                </tr>
                </thead>
                <tbody>
                {% for its in items %}
                    <tr class="productitm">
                        <td><img src="{{ MEDIA_URL }}{{ its.item.product.image }}" class="thumb"></td>
                        <td>{{ its.item.product.code|upper }}</td>
                        <td>{{ its.item.product.name }}</td>
                        <td>{{ its.item.size|upper }}</td>
                        <td>{{ its.item.product.price }}</td>
                        <td>{{ its.quantity }}</td>
                        <td class="total-price">{{ its.quantity|item_total_price:its.item.product.price }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <table class="table">
                <tr>
                    <td style="width: 59%;">
                        <table id="cart" class="table">
                            <thead>
                            <tr>
                                <th colspan="2">กรุณาเลือกวิธีการชำระเงิน</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td><input type="radio" checked></td>
                                <td class="text-left">
                                    <p>โอนเงินเข้าบัญชีธนาคาร (ที่สาขา, ตู้ ATM หรือ ออนไลน์)</p>
                                    <p><img src="{% static 'images/icon_footer_bank.jpg' %}" alt="bank transfer"
                                            style="height: auto; width: auto;">
                                        (บัญชีธนาคารจะแสดงที่หน้าถัดไปหรือในอีเมลยืนยัน)</p>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                    <td style="width: 2%;"></td>
                    <td style="width: 39%;">
                        <table style="width: 100%; background-color: #EEEEEE">
                            <tr>
                                <td colspan="2" style="padding: 10px 20px;">ราคารวมของสินค้า</td>
                                <td colspan="2" class="text-right"
                                    style="padding-right: 20px;">{{ cart.product_total }} บาท
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2" style="padding: 10px 20px;">ค่าจัดส่ง</td>
                                <td colspan="2" class="text-right"
                                    style="padding-right: 20px;">{{ cart.tax_delivery }} บาท
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2" style="padding: 10px 20px;"><b>ราคารวมทั้งหมด</b></td>
                                <td colspan="2" class="text-right" style="padding-right: 20px;">
                                    <b>{{ cart.total }} บาท</b></td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
            <div class="text-right">
                <p style="padding: 10px 0; font-size: small">*เมื่อกดปุ่ม "ยืนยันการสั่งซื้อ"
                    ระบบจะจองสินค้าให้ท่านคนเดียวทันที</p>
                <p>
                <form action="{% url 'shop:checkout_confirm' %}" method="POST">
                    {% csrf_token %}
                    <button id="checkout" class="btn btn-lg btn-success">ยืนยันการสั่งซื้อ</button>
                </form>
                </p>
            </div>
        </div>
    </div>
{% endblock %}

{% block main_script_js %}
    <script type="text/javascript">
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                notify('{{ error }}', 'error');
            {% endfor %}
        {% endif %}

        function editAddress() {
            var address_value = '{{ form.address.value }}'.replace('&lt;br /&gt;', '\r\n');
            var form = '<div class="comments-area">';
            form += '<form id="address_edit" method="POST" action="{% url "shop:update_address" %}">';
            form += "{% csrf_token %}";
            form += '<p><label for="id_email">Email:</label>{{ form.email }}</p>';
            form += '<p><label for="id_first_name">ชื่อผู้รับ:</label>{{ form.first_name }}</p>';
            form += '<p><label for="id_last_name">นามสกุล:</label>{{ form.last_name }}</p>';
            form += '<p><label for="id_address">ที่อยู่:</label><textarea cols="40" id="id_address" name="address" rows="5">' + address_value + '</textarea></p>';
            form += '<p><label for="id_province">จังหวัด:</label><div class="select-style">{% spaceless %}{{ form.province }}{% endspaceless %}</div></p>';
            form += '<p><label for="id_zipcode">รหัสไปรษณีย์:</label>{{ form.zipcode }}</p>';
            form += '<p><label for="id_phone">เบอร์โทรศัพท์: </label>{{ form.phone }}</p>';
            form += '</form>';
            alertify.confirm(form,
                function(){
                    var form = $('#address_edit');
                    form.submit();
                }
            );
        }

        function editDelivery() {
            var form = '<div class="comments-area">';
            form += '<form id="deliver_edit" method="POST" action="{% url "shop:update_delivery" %}">';
            form += "{% csrf_token %}";
            {% if request.session.deliver_by == 'ems' %}
                form += '<p><input type="radio" name="deliver_by" value="normal">ธรรมดาแบบลงทะเบียน 2-10 วัน (30 บาท)</p>';
                form += '<p><input type="radio" name="deliver_by" value="ems" checked> EMS ด่วนพิเศษ 1-2 วัน (50 บาท)</p>';
            {% else %}
                form += '<p><input type="radio" name="deliver_by" value="normal" checked>ธรรมดาแบบลงทะเบียน 2-10 วัน (30 บาท)</p>';
                form += '<p><input type="radio" name="deliver_by" value="ems"> EMS ด่วนพิเศษ 1-2 วัน (50 บาท)</p>';
            {% endif %}
            form += '</form>';
            alertify.confirm(form,
                function(){
                    var form = $('#deliver_edit');
                    form.submit();
                }
            );
        }
    </script>
{% endblock %}

shop/templates/shop/menu.html
<div class="wrap nav">
    <div class="search search-nav invisible">
        <input type="text" name="s" class="textbox" value="Search" onfocus="this.value = '';"
               onblur="if (this.value == '') {this.value = 'Search';}">
        <input type="submit" value="Subscribe" id="submit" name="submit">
        <div id="response"></div>
    </div>
    <!-- start header menu -->
    <ul class="megamenu skyblue">
        <li><a class="color1" href="{% url 'shop:index' %}">Home</a></li>
        <li><a class="color2" href="{% url 'shop:product_list' %}">Products</a></li>
        <li><a class="color3" href="{% url 'shop:article_list' %}">Article</a></li>
        <li><a class="color4" href="#">About Us</a></li>
        <li><a class="color5" href="#">Contact Us</a></li>
    </ul>
    <div class="clear"></div>
</div>