aquanine/urls.py
from django.conf.urls import url, include, patterns
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('shop.urls', namespace="shop")),
    url(r'^admin/', include('backend.urls', namespace="backend")),
    url(r'^backend/', admin.site.urls),
    url(r'^froala_editor/', include('froala_editor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if DEBUG is True it will be served automatically
if settings.DEBUG is False:
    urlpatterns += patterns('',
            url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
            url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

backend/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from backend import views
from backend.pages import announces
from backend.pages import blogs
from backend.pages import members
from backend.pages import orders

from backend.pages import products

urlpatterns = [
    # url('^',include('django.contrib.auth.urls')),
    url(r'^$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'backend:login'}, name='logout'),
    url(r'^product/$', products.ProductListView.as_view(), name='product_list'),
    url(r'^product/new/$', products.ProductAddView.as_view(), name='product_add'),
    url(r'^product/(?P<pk>[0-9]+)/$', products.ProductDetailView.as_view(), name='product_detail'),
    url(r'^product/(?P<pk>[0-9]+)/change/$', products.ProductChangeView.as_view(), name='product_change'),
    url(r'^product/(?P<pk>[0-9]+)/delete/$', products.delete_product, name='product_delete'),

    url(r'^announce/$', announces.AnnounceListView.as_view(), name='announce_list'),
    url(r'^announce/new/$', announces.AnnounceAddView.as_view(), name='announce_add'),
    url(r'^announce/(?P<pk>[0-9]+)/change/$', announces.AnnounceChangeView.as_view(), name='announce_change'),
    url(r'^announce/(?P<pk>[0-9]+)/delete/$', announces.delete_announce, name='announce_delete'),

    url(r'^member/$', members.UserListView.as_view(), name='member_list'),
    url(r'^member/new/$', members.UserAddView.as_view(), name='member_add'),
    # url(r'^member/(?P<pk>[0-9]+)/$', members.UserDetailView.as_view(), name='member_detail'),
    url(r'^member/(?P<pk>[0-9]+)/change/$', members.UserChangeView.as_view(), name='member_change'),
    url(r'^member/(?P<pk>[0-9]+)/delete/$', members.delete_user, name='member_delete'),

    url(r'^order/$', orders.OrderListView.as_view(), name='order_list'),
    url(r'^order/payment/$', orders.OrderPaymentView.as_view(), name='payment_list'),
    url(r'^order/payment/(?P<pk>[0-9]+)/(?P<status>[01])/$', orders.confirm_payment, name='payment_update'),
    url(r'^order/(?P<pk>[0-9]+)/$', orders.OrderDetailView.as_view(), name='order_detail'),

    url(r'^article/$', blogs.ArticleListView.as_view(), name='article_list'),
    url(r'^article/new/$', blogs.ArticleAddView.as_view(), name='article_add'),
    url(r'^article/(?P<pk>[0-9]+)/change/$', blogs.ArticleChangeView.as_view(), name='article_change'),
    url(r'^article/(?P<pk>[0-9]+)/delete/$', blogs.delete_article, name='article_delete'),
]

shop/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import views as auth_views

from shop import views
from shop.pages import blogs
from shop.pages import products, carts, checkouts, orders

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', auth_views.login, {'template_name': 'shop/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'shop:index'}, name='logout'),
    url(r'^signup/$', views.Signup.as_view(), name='signup'),
    url(r'^product/$', products.ProductListView.as_view(), name='product_list'),
    url(r'^product/(?P<slug>.+)/$', products.ProductDetailView.as_view(), name='product_detail'),
    url(r'^basket/$', csrf_exempt(carts.CartView.as_view()), name='cart'),
    url(r'^basket/checkout/$', checkouts.CheckoutView.as_view(), name='checkout'),
    url(r'^basket/confirm_order/$', checkouts.ConfirmCheckoutView.as_view(), name='checkout_confirm'),
    url(r'^basket/order/$', orders.OrderView.as_view(), name='order'),
    url(r'^item-count/$', views.item_count, name='item_count'),
    url(r'^payment/bank/$', orders.PaymentView.as_view(), name='payment'),
    url(r'^order/(?P<pk>[0-9]+)/confirm/$', orders.confirm_payment, name='order_confirm'),
    url(r'^order/(?P<pk>[0-9]+)/$', orders.order_detail, name='order_detail'),
    url(r'^basket/confirm_order/update/address/$', checkouts.edit_adress, name='update_address'),
    url(r'^basket/confirm_order/update/delivery/$', checkouts.edit_delivery, name='update_delivery'),
    url(r'^articles/$', blogs.BlogListView.as_view(), name='article_list'),
    url(r'^articles/(?P<slug>.+)/$', blogs.BlogDetailView.as_view(), name='article_detail'),
]

backend/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

shop/models.py
# encoding=utf8
import hashlib

from django.core.validators import RegexValidator, MinLengthValidator
from django.utils.encoding import python_2_unicode_compatible

import os

from django.db import models
from datetime import datetime, date, timedelta
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from froala_editor.fields import FroalaField

from django.utils.text import slugify

TODAY = date.today()
YESTERDAY = (TODAY - timedelta(1))
LAST2DAY = (TODAY - timedelta(2))

month_lists = ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน',
               'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม']

size_choice = (('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'))
colours_choice = (
    ('White', 'ขาว'), ('Black', 'ดำ'), ('Red', 'แดง'), ('Blue', 'น้ำเงิน'), ('Navy Blue', 'กรม'),
    ('Top Black', 'ท้อปดำ'),
    ('Top Gray', 'ท้อปเทา'), ('Black/Black', 'ดำ/ดำ'), ('Black/Red', 'ดำ/แดง'))
provinces_choice = (
    (u"กรุงเทพมหานคร", "กรุงเทพมหานคร"), (u"กระบี่", "กระบี่"), (u"กาญจนบุรี", "กาญจนบุรี"),
    (u"กาฬสินธุ์", "กาฬสินธุ์"),
    (u"กำแพงเพชร", "กำแพงเพชร"), (u"ขอนแก่น", "ขอนแก่น"), (u"จันทบุรี", "ขอนแก่น"), (u"ฉะเชิงเทรา", "ฉะเชิงเทรา"),
    (u"ชลบุรี", "ชลบุรี"), (u"ชัยนาท", "ชัยนาท"), (u"ชัยภูมิ", "ชัยภูมิ"), (u"ชุมพร", "ชุมพร"),
    (u"เชียงราย", "เชียงราย"),
    (u"เชียงใหม่", "เชียงใหม่"), (u"ตรัง", "ตรัง"), (u"ตราด", "ตราด"), (u"ตาก", "ตาก"), (u"นครนายก", "นครนายก"),
    (u"นครปฐม", "นครปฐม"), (u"นครพนม", "นครพนม"), (u"นครราชสีมา", "นครราชสีมา"), (u"นครศรีธรรมราช", "นครศรีธรรมราช"),
    (u"นครสวรรค์", "นครสวรรค์"), (u"นนทบุรี", "นนทบุรี"), (u"นราธิวาส", "นราธิวาส"), (u"น่าน", "น่าน"),
    (u"บุรีรัมย์", "บุรีรัมย์"), (u"บึงกาฬ", "บึงกาฬ"), (u"ปทุมธานี", "ปทุมธานี"),
    (u"ประจวบคีรีขันธ์", "ประจวบคีรีขันธ์"),
    (u"ปราจีนบุรี", "ปราจีนบุรี"), (u"ปัตตานี", "ปัตตานี"), (u"พระนครศรีอยุธยา", "พระนครศรีอยุธยา"),
    (u"พะเยา", "พะเยา"),
    (u"พังงา", "พังงา"), (u"พัทลุง", "พัทลุง"), (u"พิจิตร", "พิจิตร"), (u"พิษณุโลก", "พิษณุโลก"),
    (u"เพชรบุรี", "เพชรบุรี"),
    (u"เพชรบูรณ์", "เพชรบูรณ์"), (u"แพร่", "แพร่"), (u"ภูเก็ต", "ภูเก็ต"), (u"มหาสารคาม", "มหาสารคาม"),
    (u"มุกดาหาร", "มุกดาหาร"), (u"แม่ฮ่องสอน", "แม่ฮ่องสอน"), (u"ยโสธร", "ยโสธร"), (u"ยะลา", "ยะลา"),
    (u"ร้อยเอ็ด", "ร้อยเอ็ด"), (u"ระนอง", "ระนอง"), (u"ระยอง", "ระยอง"), (u"ราชบุรี", "ราชบุรี"), (u"ลพบุรี", "ลพบุรี"),
    (u"ลำปาง", "ลำปาง"), (u"ลำพูน", "ลำพูน"), (u"เลย", "เลย"), (u"ศรีสะเกษ", "ศรีสะเกษ"), (u"สกลนคร", "สกลนคร"),
    (u"สงขลา", "สงขลา"), (u"สตูล", "สตูล"), (u"สมุทรปราการ", "สมุทรปราการ"), (u"สมุทรสงคราม", "สมุทรสงคราม"),
    (u"สมุทรสาคร", "สมุทรสาคร"), (u"สระแก้ว", "สระแก้ว"), (u"สระบุรี", "สระบุรี"), (u"สิงห์บุรี", "สิงห์บุรี"),
    (u"สุโขทัย", "สุโขทัย"), (u"สุพรรณบุรี", "สุพรรณบุรี"), (u"สุราษฎร์ธานี", "สุราษฎร์ธานี"),
    (u"สุรินทร์", "สุรินทร์"),
    (u"หนองคาย", "หนองคาย"), (u"หนองบัวลำภู", "หนองบัวลำภู"), (u"อ่างทอง", "อ่างทอง"), (u"อำนาจเจริญ", "อำนาจเจริญ"),
    (u"อุดรธานี", "อุดรธานี"), (u"อุตรดิตถ์", "อุตรดิตถ์"), (u"อุทัยธานี", "อุทัยธานี"),
    (u"อุบลราชธานี", "อุบลราชธานี"))

pays_choice = (('bank', 'โอนเงินเข้าบัญชีธนาคาร (ที่สาขา, ตู้ ATM หรือ ออนไลน์)'),)
deliveries_choice = (('normal', 'ธรรมดาแบบลงทะเบียน 2-10 วัน (30 บาท)'), ('ems', 'EMS ด่วนพิเศษ 1-2 วัน (50 บาท)'))
bank_choice = (('', 'กรุณาเลือกธนาคาร'), ('scb', 'ธนาคารไทยพาณิชย์'), ('kbank', 'ธนาคารกสิกรไทย'))
last2day_choice = (('', 'กรุณาเลือกวันที่'), (TODAY, '{0} {1}'.format(TODAY.day, month_lists[TODAY.month - 1])),
                   (YESTERDAY, '{0} {1}'.format(YESTERDAY.day, month_lists[YESTERDAY.month - 1])),
                   (LAST2DAY, '{0} {1}'.format(LAST2DAY.day, month_lists[LAST2DAY.month - 1])))


def validate_image_extension(value):
    ext = os.path.splitext(value.name)[1]
    valid_extensions = ['.png', '.jpg', '.jpeg']
    if not ext.lower() in valid_extensions:
        raise ValidationError('File is not Allowed!')
    return value


def create_hash(url):
    hash = hashlib.sha1()
    hash.update(url)
    return hash.hexdigest()[:-10]


def new_filename(filename):
    extension = filename.split('.')[-1]
    filename_hash = create_hash(filename)
    subdir1 = filename_hash[-3:]
    subdir2 = filename_hash[-6:-3]
    new_filename = '{0}.{1}'.format(filename_hash, extension)
    fullpath_file = os.path.join(subdir1, subdir2, new_filename)
    return fullpath_file


def upload_file(instance, filename):
    full_path = new_filename(filename)
    return full_path


def upload_to_file(instance, filename):
    full_path = new_filename(filename)
    return u'announces/{0}'.format(full_path)


def slip_upload(instance, filename):
    full_path = new_filename(filename)
    return u'slips/{0}'.format(full_path)


def product_upload(instance, filename):
    full_path = new_filename(filename)
    return u'products/{0}'.format(full_path)


def product_upload_to_gallery(instance, filename):
    full_path = new_filename(filename)
    return u'products/{0}'.format(full_path)


@python_2_unicode_compatible
class Member(models.Model):
    user = models.OneToOneField(User)
    phone = models.CharField(max_length=20, blank=True)
    market = models.CharField(max_length=255, blank=True)
    address = models.TextField(blank=True)
    province = models.CharField(max_length=100, choices=provinces_choice, blank=True, null=True)
    zipcode = models.CharField(max_length=5, blank=True,
                               validators=[RegexValidator(r'^\d{1,5}$'), MinLengthValidator(4)])

    def __str__(self):
        return self.user.get_full_name()

    def get_full_address(self):
        return u'{0} {1} {2} {3}'.format(self.market, self.address, self.province, self.zipcode)


@python_2_unicode_compatible
class Announce(models.Model):
    name = models.CharField(max_length=255)
    start = models.DateField(default=date.today)
    end = models.DateField(blank=True, null=True)
    image = models.FileField(upload_to=upload_to_file, validators=[validate_image_extension])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Brand(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Colour(models.Model):
    name_th = models.CharField(max_length=80, blank=True)
    name_en = models.CharField(max_length=80, blank=True)

    def __str__(self):
        return u'{0} ({1})'.format(self.name_th, self.name_en)


@python_2_unicode_compatible
class Product(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=255, unique=True)
    brand = models.ForeignKey(Brand, blank=True, null=True)
    category = models.ForeignKey(Category, blank=True, null=True)
    color = models.ForeignKey(Colour, blank=True, null=True)
    price = models.DecimalField(default=0, max_digits=6, decimal_places=2)
    discount = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    detail = FroalaField(blank=True, options={'heightMin': 250})
    slug = models.SlugField(allow_unicode=True)
    image = models.FileField(upload_to=product_upload, validators=[validate_image_extension])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return u'{} - {}'.format(self.name, self.code)

    def discount_percent(self):
        return u'{}%'.format(int((1 - (self.discount / self.price)) * 100))


@python_2_unicode_compatible
class Gallery(models.Model):
    image = models.FileField(upload_to=product_upload_to_gallery, validators=[validate_image_extension])
    product = models.ForeignKey(Product)

    def __str__(self):
        return str(self.id)


@python_2_unicode_compatible
class Stock(models.Model):
    name = models.CharField(max_length=255, blank=True)
    size = models.CharField(max_length=255, choices=size_choice)
    total = models.IntegerField(default=0)
    product = models.ForeignKey(Product)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return u'{} ({})'.format(self.size, self.total)


@python_2_unicode_compatible
class CartItem(models.Model):
    cart = models.ForeignKey("Cart")
    item = models.ForeignKey(Stock)
    quantity = models.PositiveIntegerField(default=1)
    comment = models.CharField(max_length=255, default='-')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return u'{} - {}'.format(self.item.product.name, self.item.product.code)


@python_2_unicode_compatible
class Cart(models.Model):
    member = models.ForeignKey(Member, blank=True, null=True)
    items = models.ManyToManyField(Stock, through=CartItem)
    total = models.DecimalField(max_digits=50, decimal_places=2, default=0)
    product_total = models.DecimalField(max_digits=50, decimal_places=2, default=0)
    tax_delivery = models.DecimalField(max_digits=50, decimal_places=2, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.id)


@python_2_unicode_compatible
class Order(models.Model):
    member = models.ForeignKey(Member)
    cart = models.OneToOneField(Cart)
    pay_by = models.CharField(max_length=255, choices=pays_choice, blank=True, null=True)
    deliver_by = models.CharField(max_length=255, choices=deliveries_choice, blank=True, null=True)
    is_confirm = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

backend/views.py
# encoding=utf8
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import deprecate_current_app
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect
from django.shortcuts import render, resolve_url
from django.template.response import TemplateResponse
from django.utils.http import is_safe_url
from django.views import generic
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters

from backend.mixins import SuperAdminRequiredMixin


class DashboardView(SuperAdminRequiredMixin, generic.View):
    def get(self, request):
        context = {}
        return render(request, "backend/dashboard.html", context)


@deprecate_current_app
@sensitive_post_parameters()
@csrf_protect
@never_cache
def login(request, template_name='backend/login.html',
          redirect_field_name=REDIRECT_FIELD_NAME, authentication_form=AuthenticationForm, extra_context=None):
    """
    Displays the login form and handles the login action.
    """
    redirect_to = request.POST.get(redirect_field_name,
                                   request.GET.get(redirect_field_name, ''))

    if request.method == "POST":
        form = authentication_form(request, data=request.POST)
        if form.is_valid():

            # Ensure the user-originating redirection url is safe.
            if not is_safe_url(url=redirect_to, host=request.get_host()):
                redirect_to = resolve_url('backend:dashboard')

            # Okay, security check complete. Log the user in.
            auth_login(request, form.get_user())

            return HttpResponseRedirect(redirect_to)
    else:
        form = authentication_form(request)

    current_site = get_current_site(request)

    context = {
        'form': form,
        redirect_field_name: redirect_to,
        'site': current_site,
        'site_name': current_site.name,
    }
    if extra_context is not None:
        context.update(extra_context)

    return TemplateResponse(request, template_name, context)

backend/templates/backend/products/detail.html
{% extends 'backend/base.html' %}
{% load staticfiles table_tags %}

{% block title %}
    {{ object }}
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'backend:product_list' %}">สินค้า</a></li>
    <li class="active">{{ object }}</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>{{ object }}</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <div class="col-md-7 col-sm-7 col-xs-12">
                        <div class="product-image">
                            <img src="{{ MEDIA_URL }}{{ object.image }}" alt="{{ object }}"/>
                        </div>

                        <div class="text-center">
                            <a href="{% url 'backend:product_change' object.id %}" class="btn btn-warning"><i
                                    class="fa fa-pencil"></i> แก้ไขข้อมูล</a>
                            <a href="{% url 'backend:product_delete' object.id %}" class="btn btn-danger"
                               onclick="return confirm('คุณต้องการลบสินค้าชิ้นนี้หรือไม่?');"><i
                                    class="fa fa-trash"></i> ลบสินค้า</a>
                        </div>
                    </div>

                    <div class="col-md-5 col-sm-5 col-xs-12" style="border:0px solid #e5e5e5;">

                        <h3 class="prod_title">{{ object }}</h3>
                        <h2>รหัสสินค้า :
                            <small>{{ object.code|upper }}</small>
                        </h2>
                        <h2>สี :
                            <small>{{ object.color }}</small>
                        </h2>

                        <div class="">
                            <h2>สินค้าใน Stock</h2>
                            <table class="table table-striped table-hover text-center">
                                <thead>
                                <tr>
                                    <td>Size</td>
                                    <td>Total</td>
                                </tr>
                                </thead>
                                <tbody>
                                {% for item in object.stock_set.all %}
                                    <tr>
                                        <td>{{ item.size|upper }}</td>
                                        <td>{{ item.total }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>

                        <div class="">
                            <div class="product_price">
                                {% if object.discount %}
                                    <h1 class="price">ราคา:
                                        <del>{{ object.price }} บาท</del>
                                    </h1>
                                    <span class="price-tax">ลดเหลือ: {{ object.discount }} บาท</span>
                                {% else %}
                                    <h1 class="price">ราคา: {{ object.price }} บาท</h1>
                                    <span class="price-tax">ลดเหลือ: - บาท</span>
                                {% endif %}
                                <br>
                            </div>
                        </div>

                        <div>
                            <h2>Galleries</h2>
                            <div class="product_gallery">
                                {% for gallery in object.gallery_set.all %}
                                    <a>
                                        <img src="{{ MEDIA_URL }}{{ gallery.image }}" alt="{{ object }}"/>
                                    </a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>


                    <div class="col-md-12">
                        <h4>รายละเอียดสินค้า</h4>
                        <legend class="section"></legend>
                        {% if object.detail %}
                            <p>{{ object.detail }}</p>
                        {% else %}
                            <p>-</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

backend/templates/backend/products/lists.html
{% extends 'backend/base.html' %}
{% load staticfiles table_tags %}

{% block title %}
    รายการสินค้า
{% endblock %}

{% block breadcrumbs %}
    <li class="active">สินค้า</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>รายการสินค้า</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a href="{% url 'backend:product_add' %}"><i class="fa fa-plus"></i> เพิ่มสินค้าใหม่</a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    {% render_table products %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

backend/templates/backend/products/new.html
{% extends 'backend/base.html' %}
{% load staticfiles backend_tags %}

{% block title %}
    เพิ่มสินค้าใหม่
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'backend:product_list' %}">สินค้า</a></li>
    <li class="active">ใหม่</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>เพิ่มสินค้าใหม่</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <form class="form-horizontal" method="POST" action="{% url 'backend:product_add' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}" class="col-sm-1 control-label">{{ field.label }}</label>
                            {% for error in field.errors %}
                                <strong>{{ error|escape }}</strong>
                            {% endfor %}
                            <div class="col-sm-11">
                                {{ field }}
                            </div>
                        </div>
                        {% endfor %}

                        <label class="control-label">Stock Item</label>
                        {{ stock_formset.management_form }}
                        <table class="table">
                            {% for form_set in stock_formset.forms %}
                                <tr class="formset">
                                    {% for hidden in form_set.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                    {% for field in form_set.visible_fields %}
                                        <td>
                                            <div class="form-group">
                                                <label for="{{ field.id_for_label }}" class="col-sm-3 control-label">{{ field.label }}: </label>
                                                <div class="col-sm-9">
                                                    {% for error in field.errors %}
                                                        <strong>{{ error|escape }}</strong>
                                                    {% endfor %}
                                                    {{ field }}
                                                </div>
                                            </div>
                                        </td>
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        </table>

                        <label class="control-label">Gallery</label>
                        <legend class="section"></legend>
                        {{ gallery_formset.management_form }}
                        <table class="table">
                            {% for form_set in gallery_formset.forms %}
                                <tr class="formset-image">
                                    {% for hidden in form_set.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                    {% for field in form_set.visible_fields %}
                                        <td>
                                            <div class="form-group">
                                                <label for="{{ field.id_for_label }}" class="col-sm-12 control-label">{{ field.label }}: </label>
                                                <div class="col-sm-10">
                                                    {% for error in field.errors %}
                                                        <strong>{{ error|escape }}</strong>
                                                    {% endfor %}
                                                    {{ field }}
                                                </div>
                                            </div>
                                        </td>
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        </table>
                        <div class="text-right">
                            <button type="submit" class="btn btn-info">บันทึก</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_js %}
    <script type="text/javascript">
        var add_txt = '<button class="btn btn-default"><i class="fa fa-plus"> Add Other</button>';
        var remove_txt = '<button class="btn btn-danger"><i class="fa fa-trash"> Remove</button>';
        $('.formset').formset({
            prefix: '{{ stock_formset.prefix }}',
            addText: add_txt,
            deleteText: remove_txt
        });
        $('.formset-image').formset({
            prefix: '{{ gallery_formset.prefix }}',
            addText: add_txt,
            deleteText: remove_txt
        });
    </script>
{% endblock %}